import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH });
const page = await browser.newPage({ viewport: { width: 1180, height: 820 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto('http://127.0.0.1:4173');
await page.waitForLoadState('networkidle');
await page.waitForFunction(() => document.querySelector('[data-action="start"]:not([disabled])'), { timeout: 20000 });
await mkdir('artifacts', { recursive: true });
await page.screenshot({ path: 'artifacts/home.png', fullPage: true });
console.log('首页按钮', await page.getByRole('button').allTextContents());
await page.getByRole('button', { name: '开始玩' }).click();
await page.waitForSelector('.pot-items');
await page.screenshot({ path: 'artifacts/game.png', fullPage: true });
console.log('游戏按钮', await page.getByRole('button').allTextContents());
await page.context().setOffline(true);
await page.reload();
await page.waitForSelector('[data-action="resume"]:not([disabled])');
await page.locator('[data-action="resume"]').click();
const offlineAudio = await page.evaluate(async () => {
  const r = await fetch('./assets/audio/rabbit/welcome.mp3', { headers: { Range: 'bytes=0-99' } });
  return { status: r.status, bytes: (await r.arrayBuffer()).byteLength };
});
if (offlineAudio.status !== 206 || offlineAudio.bytes !== 100) throw new Error('最终版本离线音频验证失败');
console.log('最终版本离线启动及音频 Range 验证通过');
console.log('errors', errors);
if (errors.length) throw new Error(errors.join('\n'));
await browser.close();
